dotenv: .env
# add new network is: brownie networks add Ethereum ganache-local host=https://127.0.0.1:7545 chainid=5777
networks:
  development:
    verify: False
  ganache-local:
    verify: False
  goerli:
    eth_usd_price_feed_address: '0xEC398a9dDcaf0814faDa80F345e8469F64aDA3A7'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed_address: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
wallets:
  from_key: ${PRIVATE_KEY}
